FROM centos:7
MAINTAINER Sander <mail@sandervanvugt.nl>

# Add repo file
COPY ./sander.repo /etc/yum.repos.d/

# Install cool software
RUN 	yum -y update 
RUN	yum -y install bash nmap iproute 
RUN	yum clean all

ENTRYPOINT ["/usr/bin/nmap"]
CMD ["-sn", "172.17.0.0/24"] 
